spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_resource_booking?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}         # 这里写你的 MySQL 用户名
    password: ${DB_PASSWORD:123456}       # 这里写你的 MySQL 密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # 自动建表 (开发推荐 update，生产推荐 validate)
    show-sql: true         # 控制台打印 SQL
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080               # 运行端口，默认 8080，不冲突就不用改
